// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using Kentico.Kontent.Delivery.Abstractions;
using System.Collections.Generic;

namespace Kontent.Models
{
    public partial class TrainingCourseModel
    {
        public const string Codename = "training_course2";
        public const string DescriptionCodename = "description";
        public const string TitleCodename = "title";
        public const string UrlCodename = "url";
        public const string NextInPathCodename = "next_in_path";

        public string Description { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
        public IEnumerable<TrainingCourseModel> NextInPath { get; set; }
        public string Url { get; set; }
    }
}